# Generated by Django 2.1.5 on 2019-02-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientDef',
            fields=[
                ('Nutr_No', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Units', models.CharField(max_length=7)),
                ('Tagname', models.CharField(blank=True, max_length=20, null=True)),
                ('NutrDesc', models.CharField(max_length=60)),
                ('Num_Dec', models.CharField(max_length=1)),
                ('SR_Order', models.DecimalField(decimal_places=6, max_digits=48)),
            ],
        ),
    ]
