# Generated by Django 2.1.5 on 2019-02-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0002_nutrientdef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='Nutr_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrient.NutrientDef'),
        ),
    ]
