# Generated by Django 2.1.5 on 2019-02-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrient', '0003_auto_20190223_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='NDB_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='nutrient.Ingredient'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='Nutr_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_def', to='nutrient.NutrientDef'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='NDB_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='nutrient.Ingredient'),
        ),
    ]
